server.port=${PORT:8081}
spring.application.name=wallet-service
spring.config.import=optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888}

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/wallet_db}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

management.endpoints.web.exposure.include=health,info,metrics
app.jwt.secret=${APP_JWT_SECRET:dev-secret-change-me-not-for-production-000}
app.internal.secret=${INTERNAL_SECRET:dev-internal-key-change-me}
